#!/bin/bash

export DEFINES="
AUDIO_REACTIVE
FBX_SUPPORTED
PASSTHROUGH_SUPPORTED
SELECTION_ON
TILT_BRUSH
UNITY_2017_2_OR_NEWER
UNITY_2018_4_OR_NEWER
UNITY_2019_3_OR_NEWER
UNITY_2020_3_OR_NEWER
UNITY_5_4_OR_NEWER
UNITY_5_6_OR_NEWER
UNITY_EDITOR
UNITY_EDITOR_WIN
UNITY_STANDALONE_WIN
UNITY_WIN
USD_SUPPORTED
USE_TILT_BRUSH_CPP
"
./pre_commit_dotnet_format.sh "$@"
