#!/bin/bash

export DEFINES="
FORCE_FOCUSAWARE
FORCE_HEADTRACKING
FORCE_QUEST_SUPPORT_DEVICE
OCULUS_SUPPORTED
PASSTHROUGH_SUPPORTED
TILT_BRUSH
UNITY_2017_2_OR_NEWER
UNITY_2018_4_OR_NEWER
UNITY_2019_3_OR_NEWER
UNITY_2020_3_OR_NEWER
UNITY_5_4_OR_NEWER
UNITY_5_6_OR_NEWER
UNITY_ANDROID
UNITY_EDITOR
USE_TILT_BRUSH_CPP
"
./pre_commit_dotnet_format.sh "$@"
