//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.2
//     from Assets/Scripts/Input/UnityXRInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace TiltBrush
{
    public partial class @UnityXRInputAction : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @UnityXRInputAction()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""UnityXRInput"",
    ""maps"": [
        {
            ""name"": ""Brush"",
            ""id"": ""0be8ce9b-abc7-4f34-9bb4-a4aa0c9582e3"",
            ""actions"": [
                {
                    ""name"": ""TriggerAxis"",
                    ""type"": ""Value"",
                    ""id"": ""f8e2a4d8-2611-42f7-b863-6102c7f22312"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TriggerButton"",
                    ""type"": ""Button"",
                    ""id"": ""6ed563ff-a250-4d2f-8b14-d1fe360a2470"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TriggerTouch"",
                    ""type"": ""Button"",
                    ""id"": ""3544fe23-65ae-415c-ab58-721dfc92223b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThumbAxis"",
                    ""type"": ""Value"",
                    ""id"": ""3b226d8b-8fc0-4879-84d7-1c25db6e34b5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PadAxis"",
                    ""type"": ""Value"",
                    ""id"": ""a081885f-255a-4817-a12c-b6d9dd842582"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PadButton"",
                    ""type"": ""Button"",
                    ""id"": ""f65d1a3b-57ec-4f58-b5e9-476f9ddbcaa7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PadTouch"",
                    ""type"": ""Button"",
                    ""id"": ""680cd601-aae8-4fb8-8d1d-51eb23c17941"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GripAxis"",
                    ""type"": ""Value"",
                    ""id"": ""f040e383-e8c2-4f56-86f6-1ca48eb552e2"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""GripButton"",
                    ""type"": ""Value"",
                    ""id"": ""c27a451f-8196-4911-b54c-4ad40c55efe8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PrimaryTouch"",
                    ""type"": ""Button"",
                    ""id"": ""9c7136cb-868c-49dc-ac53-cebeefd3de69"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrimaryButton"",
                    ""type"": ""Button"",
                    ""id"": ""7e497fba-b632-4c20-b4a7-e1aa457cd785"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryTouch"",
                    ""type"": ""Button"",
                    ""id"": ""b63ff496-95b8-4da7-b3fe-3dc8a3151097"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryButton"",
                    ""type"": ""Button"",
                    ""id"": ""0d49ad6c-bc4d-4488-9416-eca803bf1ced"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7cb5d70d-9271-49e9-b13e-63071ecb271f"",
                    ""path"": ""<XRController>{RightHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c70e565b-1c0f-4d60-b284-ccdec2fd856d"",
                    ""path"": ""<XRController>{RightHand}/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fbd220cf-4b28-42eb-8112-d150759e76e3"",
                    ""path"": ""<XRController>{RightHand}/joystick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThumbAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eb790e8d-afc9-4f2d-bdcf-51951724286f"",
                    ""path"": ""<XRController>{RightHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThumbAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d172b06b-b295-4491-aabb-d67cdb987182"",
                    ""path"": ""<XRController>{RightHand}/grip"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""HTC Vive Controller;Oculus Touch Controller;WMR Controller"",
                    ""action"": ""GripAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6bc6c02c-4693-4eac-ad02-04edc00cc05f"",
                    ""path"": ""<XRController>{RightHand}/gripForce"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Index Controller"",
                    ""action"": ""GripAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""34e41acb-65d2-4ab3-b058-f2c13687d92d"",
                    ""path"": ""<XRController>{RightHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""HTC Vive Controller;Oculus Touch Controller;WMR Controller"",
                    ""action"": ""GripButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c75c3e6d-ed3e-449d-8d19-f59102626f6a"",
                    ""path"": ""<XRController>{RightHand}/primaryTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryTouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6bd04bcc-1fec-4fa2-9e42-aa42f0219a65"",
                    ""path"": ""<XRController>{RightHand}/secondaryTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryTouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0acf7b79-2507-4ee7-95a4-7476c9d380d2"",
                    ""path"": ""<XRController>{RightHand}/triggerTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerTouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""59a64469-581c-4de0-8720-ce44496452c6"",
                    ""path"": ""<XRController>{RightHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""898675f7-d41c-4a73-9b8e-0b847656c2f3"",
                    ""path"": ""<XRController>{RightHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d38db390-e23f-499c-b7e2-5424fae71eb5"",
                    ""path"": ""<XRController>{RightHand}/touchpadTouch"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PadTouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b2c72d2f-d8e2-4f8f-976b-76d343580c0d"",
                    ""path"": ""<XRController>{RightHand}/trackpadTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PadTouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ac7c1ff5-f16e-4d6d-a7ca-b3fb7297e6c5"",
                    ""path"": ""<XRController>{RightHand}/thumbstickTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PadTouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25445e46-6ad3-4aef-b447-f33be3ea01ee"",
                    ""path"": ""<XRController>{RightHand}/thumbstickClicked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PadButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""946e923e-f3b0-4b4c-86aa-b93d7e2f05ca"",
                    ""path"": ""<XRController>{RightHand}/joystickClicked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PadButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bdc39c64-9dac-47a6-8a92-9ce8d493e197"",
                    ""path"": ""<XRController>{RightHand}/touchpadClick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""HTC Vive Controller"",
                    ""action"": ""PadButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e2134103-3299-4a1e-9bb8-d23c02b7a2a1"",
                    ""path"": ""<XRController>{RightHand}/trackpadClicked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""HTC Vive Controller"",
                    ""action"": ""PadButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f8f0b458-eaf4-48b6-b8c7-18e189a62831"",
                    ""path"": ""<XRController>{RightHand}/touchpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PadAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f29e1937-1a11-4fa8-aecd-f392c83be231"",
                    ""path"": ""<XRController>{RightHand}/trackpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PadAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Pad Right"",
                    ""id"": ""2ebfb718-c777-42c4-975a-2c1b95c7b9ff"",
                    ""path"": ""VivePadButton(min=0.1,max=1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryButton"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""padButton"",
                    ""id"": ""7d7a589a-5c5a-4639-87e2-d35af20eaa27"",
                    ""path"": ""<XRController>{RightHand}/trackpadClicked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""HTC Vive Controller"",
                    ""action"": ""SecondaryButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""axisToModify"",
                    ""id"": ""e1e38b8d-d589-4bed-bba6-8077a416f1ad"",
                    ""path"": ""<XRController>{RightHand}/trackpad/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""HTC Vive Controller"",
                    ""action"": ""SecondaryButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Pad Left"",
                    ""id"": ""7a934ba3-3ece-417f-8993-713e4e646425"",
                    ""path"": ""VivePadButton(min=-1,max=-0.1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryButton"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""padButton"",
                    ""id"": ""789a8d32-17b1-4518-ad85-123ee4871bc7"",
                    ""path"": ""<XRController>{RightHand}/trackpadClicked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""HTC Vive Controller"",
                    ""action"": ""PrimaryButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""axisToModify"",
                    ""id"": ""2b21db98-9d6c-49bd-9cc1-9e117ad78504"",
                    ""path"": ""<XRController>{RightHand}/trackpad/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""HTC Vive Controller"",
                    ""action"": ""PrimaryButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""003127ee-6573-4af2-96c7-f007ac20ae79"",
                    ""path"": ""<XRController>{RightHand}/gripForce"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Index Controller"",
                    ""action"": ""GripButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Wand"",
            ""id"": ""41556884-8b0f-4112-9d11-154bffb66fc5"",
            ""actions"": [
                {
                    ""name"": ""TriggerAxis"",
                    ""type"": ""Value"",
                    ""id"": ""6f3c2146-e8c7-48df-84d4-29901c1cf05d"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TriggerButton"",
                    ""type"": ""Button"",
                    ""id"": ""0234ab5e-3ce9-4679-98a0-fc488101d967"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TriggerTouch"",
                    ""type"": ""Button"",
                    ""id"": ""914734cd-5995-4916-b266-800c79239de4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThumbAxis"",
                    ""type"": ""Value"",
                    ""id"": ""e41c4f21-7ab6-4aca-b44c-c0104cf6220f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PadAxis"",
                    ""type"": ""Value"",
                    ""id"": ""ce8f3b76-f6a2-4f34-810e-0d25b17edeba"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PadButton"",
                    ""type"": ""Button"",
                    ""id"": ""92125b9c-717c-4d2b-830d-40d45f19e488"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PadTouch"",
                    ""type"": ""Button"",
                    ""id"": ""f719a045-3f3b-4061-a603-65486c14ac6a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GripAxis"",
                    ""type"": ""Value"",
                    ""id"": ""7bce9bba-4f1b-4564-b97f-746b1703f963"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""GripButton"",
                    ""type"": ""Button"",
                    ""id"": ""6e87be1c-8de3-4a76-b980-87e0915d518e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrimaryTouch"",
                    ""type"": ""Button"",
                    ""id"": ""190b2b7c-7906-43b4-8816-fce1b637abd6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrimaryButton"",
                    ""type"": ""Button"",
                    ""id"": ""3db202da-1c68-4d82-8791-59f71c8087d4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryTouch"",
                    ""type"": ""Button"",
                    ""id"": ""2e4c62b6-e52b-4df2-b25b-937c3000e9f1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryButton"",
                    ""type"": ""Button"",
                    ""id"": ""39846e4e-38e0-4d04-a16b-73a2dfa49299"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1d36f7c4-e15f-44e6-9b43-be5aa1f31506"",
                    ""path"": ""<XRController>{LeftHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0628fcd0-02fd-46a5-908d-be872ee44fc1"",
                    ""path"": ""<XRController>{LeftHand}/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""018af670-cf00-4c9d-b244-282db1a6451d"",
                    ""path"": ""<XRController>{LeftHand}/touchpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PadAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""adeeb6c7-82ae-42ee-a782-3acf394099c1"",
                    ""path"": ""<XRController>{LeftHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PadAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e29be70f-1153-420f-926c-927b472a4610"",
                    ""path"": ""<XRController>{LeftHand}/grip"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""HTC Vive Controller;Oculus Touch Controller;WMR Controller"",
                    ""action"": ""GripAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c16d376c-ec23-4bc6-9424-9296529d2793"",
                    ""path"": ""<XRController>{LeftHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""HTC Vive Controller;Oculus Touch Controller;WMR Controller"",
                    ""action"": ""GripButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9731457f-5459-4529-8c6b-270417cf667e"",
                    ""path"": ""<XRController>{LeftHand}/primaryTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryTouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""81341afd-de4e-480d-955c-6187281e6042"",
                    ""path"": ""<XRController>{LeftHand}/secondaryTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryTouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0eff34a3-b731-49fe-b613-0ab518b11f1b"",
                    ""path"": ""<XRController>{LeftHand}/triggerTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerTouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7904b06f-c66c-4f23-8f3c-0d7b0048ba88"",
                    ""path"": ""<XRController>{LeftHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7df85a5a-db19-43e1-8a23-10289ec655db"",
                    ""path"": ""<XRController>{LeftHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""094e043e-aa39-42cc-979d-4121c9492f66"",
                    ""path"": ""<XRController>{LeftHand}/touchpadTouch"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PadTouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c77ac70-3fc9-496e-93c8-eb8f5ea4ff4a"",
                    ""path"": ""<XRController>{LeftHand}/trackpadTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PadTouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""11ed09ea-9d13-40c3-851e-001d13a11f90"",
                    ""path"": ""<XRController>{LeftHand}/thumbstickTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PadTouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e2bda33b-a593-44d7-a4ff-9f17e469d3be"",
                    ""path"": ""<XRController>{LeftHand}/thumbstickClicked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PadButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7d663301-739f-4527-b71e-9e419eda5c00"",
                    ""path"": ""<XRController>{LeftHand}/touchpadClick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PadButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d15cbbc8-5139-449a-a348-6cda45ffd92a"",
                    ""path"": ""<XRController>{LeftHand}/joystickClicked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PadButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9c308136-c1af-45a0-b5f5-9e804331f1ca"",
                    ""path"": ""<XRController>{LeftHand}/trackpadClicked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PadButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""15d6fc3c-b403-487d-b3fb-329ad6c3c2da"",
                    ""path"": ""<XRController>{LeftHand}/joystick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThumbAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a3fb06e5-2137-4e33-977d-a229b3578b56"",
                    ""path"": ""<XRController>{LeftHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThumbAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Vive Pad Right"",
                    ""id"": ""4870119a-fffc-449f-bb51-3ae912068789"",
                    ""path"": ""VivePadButton(min=0.1,max=1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryButton"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""padButton"",
                    ""id"": ""ca4a4aa2-0bbe-4a45-9d2f-57f833b5707c"",
                    ""path"": ""<XRController>{LeftHand}/trackpadClicked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""HTC Vive Controller"",
                    ""action"": ""SecondaryButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""axisToModify"",
                    ""id"": ""8ad41a33-9308-403b-95fc-d54bb3687dce"",
                    ""path"": ""<XRController>{LeftHand}/trackpad/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""HTC Vive Controller"",
                    ""action"": ""SecondaryButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Pad Left"",
                    ""id"": ""0c7ffe69-898f-4d53-b66f-41f4ea0da3a4"",
                    ""path"": ""VivePadButton(min=-1,max=-0.1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryButton"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""padButton"",
                    ""id"": ""c59eeed9-cd72-4533-a70e-2cf8ea386489"",
                    ""path"": ""<XRController>{LeftHand}/trackpadClicked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""HTC Vive Controller"",
                    ""action"": ""PrimaryButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""axisToModify"",
                    ""id"": ""52a7e2df-742c-4fcf-a41f-66a37c66e9cd"",
                    ""path"": ""<XRController>{LeftHand}/trackpad/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""HTC Vive Controller"",
                    ""action"": ""PrimaryButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""a9ac6fbd-6257-4c59-a22b-1d2c497dca49"",
                    ""path"": ""<XRController>{LeftHand}/gripForce"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Index Controller"",
                    ""action"": ""GripAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a4ddb938-ad49-405f-928d-2419a98c0a78"",
                    ""path"": ""<XRController>{LeftHand}/gripForce"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Index Controller"",
                    ""action"": ""GripButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Index Controller"",
            ""bindingGroup"": ""Index Controller"",
            ""devices"": [
                {
                    ""devicePath"": ""<ValveIndexController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""HTC Vive Controller"",
            ""bindingGroup"": ""HTC Vive Controller"",
            ""devices"": [
                {
                    ""devicePath"": ""<ViveController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Oculus Touch Controller"",
            ""bindingGroup"": ""Oculus Touch Controller"",
            ""devices"": [
                {
                    ""devicePath"": ""<OculusTouchController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""WMR Controller"",
            ""bindingGroup"": ""WMR Controller"",
            ""devices"": [
                {
                    ""devicePath"": ""<WMRSpatialController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
            // Brush
            m_Brush = asset.FindActionMap("Brush", throwIfNotFound: true);
            m_Brush_TriggerAxis = m_Brush.FindAction("TriggerAxis", throwIfNotFound: true);
            m_Brush_TriggerButton = m_Brush.FindAction("TriggerButton", throwIfNotFound: true);
            m_Brush_TriggerTouch = m_Brush.FindAction("TriggerTouch", throwIfNotFound: true);
            m_Brush_ThumbAxis = m_Brush.FindAction("ThumbAxis", throwIfNotFound: true);
            m_Brush_PadAxis = m_Brush.FindAction("PadAxis", throwIfNotFound: true);
            m_Brush_PadButton = m_Brush.FindAction("PadButton", throwIfNotFound: true);
            m_Brush_PadTouch = m_Brush.FindAction("PadTouch", throwIfNotFound: true);
            m_Brush_GripAxis = m_Brush.FindAction("GripAxis", throwIfNotFound: true);
            m_Brush_GripButton = m_Brush.FindAction("GripButton", throwIfNotFound: true);
            m_Brush_PrimaryTouch = m_Brush.FindAction("PrimaryTouch", throwIfNotFound: true);
            m_Brush_PrimaryButton = m_Brush.FindAction("PrimaryButton", throwIfNotFound: true);
            m_Brush_SecondaryTouch = m_Brush.FindAction("SecondaryTouch", throwIfNotFound: true);
            m_Brush_SecondaryButton = m_Brush.FindAction("SecondaryButton", throwIfNotFound: true);
            // Wand
            m_Wand = asset.FindActionMap("Wand", throwIfNotFound: true);
            m_Wand_TriggerAxis = m_Wand.FindAction("TriggerAxis", throwIfNotFound: true);
            m_Wand_TriggerButton = m_Wand.FindAction("TriggerButton", throwIfNotFound: true);
            m_Wand_TriggerTouch = m_Wand.FindAction("TriggerTouch", throwIfNotFound: true);
            m_Wand_ThumbAxis = m_Wand.FindAction("ThumbAxis", throwIfNotFound: true);
            m_Wand_PadAxis = m_Wand.FindAction("PadAxis", throwIfNotFound: true);
            m_Wand_PadButton = m_Wand.FindAction("PadButton", throwIfNotFound: true);
            m_Wand_PadTouch = m_Wand.FindAction("PadTouch", throwIfNotFound: true);
            m_Wand_GripAxis = m_Wand.FindAction("GripAxis", throwIfNotFound: true);
            m_Wand_GripButton = m_Wand.FindAction("GripButton", throwIfNotFound: true);
            m_Wand_PrimaryTouch = m_Wand.FindAction("PrimaryTouch", throwIfNotFound: true);
            m_Wand_PrimaryButton = m_Wand.FindAction("PrimaryButton", throwIfNotFound: true);
            m_Wand_SecondaryTouch = m_Wand.FindAction("SecondaryTouch", throwIfNotFound: true);
            m_Wand_SecondaryButton = m_Wand.FindAction("SecondaryButton", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Brush
        private readonly InputActionMap m_Brush;
        private IBrushActions m_BrushActionsCallbackInterface;
        private readonly InputAction m_Brush_TriggerAxis;
        private readonly InputAction m_Brush_TriggerButton;
        private readonly InputAction m_Brush_TriggerTouch;
        private readonly InputAction m_Brush_ThumbAxis;
        private readonly InputAction m_Brush_PadAxis;
        private readonly InputAction m_Brush_PadButton;
        private readonly InputAction m_Brush_PadTouch;
        private readonly InputAction m_Brush_GripAxis;
        private readonly InputAction m_Brush_GripButton;
        private readonly InputAction m_Brush_PrimaryTouch;
        private readonly InputAction m_Brush_PrimaryButton;
        private readonly InputAction m_Brush_SecondaryTouch;
        private readonly InputAction m_Brush_SecondaryButton;
        public struct BrushActions
        {
            private @UnityXRInputAction m_Wrapper;
            public BrushActions(@UnityXRInputAction wrapper) { m_Wrapper = wrapper; }
            public InputAction @TriggerAxis => m_Wrapper.m_Brush_TriggerAxis;
            public InputAction @TriggerButton => m_Wrapper.m_Brush_TriggerButton;
            public InputAction @TriggerTouch => m_Wrapper.m_Brush_TriggerTouch;
            public InputAction @ThumbAxis => m_Wrapper.m_Brush_ThumbAxis;
            public InputAction @PadAxis => m_Wrapper.m_Brush_PadAxis;
            public InputAction @PadButton => m_Wrapper.m_Brush_PadButton;
            public InputAction @PadTouch => m_Wrapper.m_Brush_PadTouch;
            public InputAction @GripAxis => m_Wrapper.m_Brush_GripAxis;
            public InputAction @GripButton => m_Wrapper.m_Brush_GripButton;
            public InputAction @PrimaryTouch => m_Wrapper.m_Brush_PrimaryTouch;
            public InputAction @PrimaryButton => m_Wrapper.m_Brush_PrimaryButton;
            public InputAction @SecondaryTouch => m_Wrapper.m_Brush_SecondaryTouch;
            public InputAction @SecondaryButton => m_Wrapper.m_Brush_SecondaryButton;
            public InputActionMap Get() { return m_Wrapper.m_Brush; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(BrushActions set) { return set.Get(); }
            public void SetCallbacks(IBrushActions instance)
            {
                if (m_Wrapper.m_BrushActionsCallbackInterface != null)
                {
                    @TriggerAxis.started -= m_Wrapper.m_BrushActionsCallbackInterface.OnTriggerAxis;
                    @TriggerAxis.performed -= m_Wrapper.m_BrushActionsCallbackInterface.OnTriggerAxis;
                    @TriggerAxis.canceled -= m_Wrapper.m_BrushActionsCallbackInterface.OnTriggerAxis;
                    @TriggerButton.started -= m_Wrapper.m_BrushActionsCallbackInterface.OnTriggerButton;
                    @TriggerButton.performed -= m_Wrapper.m_BrushActionsCallbackInterface.OnTriggerButton;
                    @TriggerButton.canceled -= m_Wrapper.m_BrushActionsCallbackInterface.OnTriggerButton;
                    @TriggerTouch.started -= m_Wrapper.m_BrushActionsCallbackInterface.OnTriggerTouch;
                    @TriggerTouch.performed -= m_Wrapper.m_BrushActionsCallbackInterface.OnTriggerTouch;
                    @TriggerTouch.canceled -= m_Wrapper.m_BrushActionsCallbackInterface.OnTriggerTouch;
                    @ThumbAxis.started -= m_Wrapper.m_BrushActionsCallbackInterface.OnThumbAxis;
                    @ThumbAxis.performed -= m_Wrapper.m_BrushActionsCallbackInterface.OnThumbAxis;
                    @ThumbAxis.canceled -= m_Wrapper.m_BrushActionsCallbackInterface.OnThumbAxis;
                    @PadAxis.started -= m_Wrapper.m_BrushActionsCallbackInterface.OnPadAxis;
                    @PadAxis.performed -= m_Wrapper.m_BrushActionsCallbackInterface.OnPadAxis;
                    @PadAxis.canceled -= m_Wrapper.m_BrushActionsCallbackInterface.OnPadAxis;
                    @PadButton.started -= m_Wrapper.m_BrushActionsCallbackInterface.OnPadButton;
                    @PadButton.performed -= m_Wrapper.m_BrushActionsCallbackInterface.OnPadButton;
                    @PadButton.canceled -= m_Wrapper.m_BrushActionsCallbackInterface.OnPadButton;
                    @PadTouch.started -= m_Wrapper.m_BrushActionsCallbackInterface.OnPadTouch;
                    @PadTouch.performed -= m_Wrapper.m_BrushActionsCallbackInterface.OnPadTouch;
                    @PadTouch.canceled -= m_Wrapper.m_BrushActionsCallbackInterface.OnPadTouch;
                    @GripAxis.started -= m_Wrapper.m_BrushActionsCallbackInterface.OnGripAxis;
                    @GripAxis.performed -= m_Wrapper.m_BrushActionsCallbackInterface.OnGripAxis;
                    @GripAxis.canceled -= m_Wrapper.m_BrushActionsCallbackInterface.OnGripAxis;
                    @GripButton.started -= m_Wrapper.m_BrushActionsCallbackInterface.OnGripButton;
                    @GripButton.performed -= m_Wrapper.m_BrushActionsCallbackInterface.OnGripButton;
                    @GripButton.canceled -= m_Wrapper.m_BrushActionsCallbackInterface.OnGripButton;
                    @PrimaryTouch.started -= m_Wrapper.m_BrushActionsCallbackInterface.OnPrimaryTouch;
                    @PrimaryTouch.performed -= m_Wrapper.m_BrushActionsCallbackInterface.OnPrimaryTouch;
                    @PrimaryTouch.canceled -= m_Wrapper.m_BrushActionsCallbackInterface.OnPrimaryTouch;
                    @PrimaryButton.started -= m_Wrapper.m_BrushActionsCallbackInterface.OnPrimaryButton;
                    @PrimaryButton.performed -= m_Wrapper.m_BrushActionsCallbackInterface.OnPrimaryButton;
                    @PrimaryButton.canceled -= m_Wrapper.m_BrushActionsCallbackInterface.OnPrimaryButton;
                    @SecondaryTouch.started -= m_Wrapper.m_BrushActionsCallbackInterface.OnSecondaryTouch;
                    @SecondaryTouch.performed -= m_Wrapper.m_BrushActionsCallbackInterface.OnSecondaryTouch;
                    @SecondaryTouch.canceled -= m_Wrapper.m_BrushActionsCallbackInterface.OnSecondaryTouch;
                    @SecondaryButton.started -= m_Wrapper.m_BrushActionsCallbackInterface.OnSecondaryButton;
                    @SecondaryButton.performed -= m_Wrapper.m_BrushActionsCallbackInterface.OnSecondaryButton;
                    @SecondaryButton.canceled -= m_Wrapper.m_BrushActionsCallbackInterface.OnSecondaryButton;
                }
                m_Wrapper.m_BrushActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @TriggerAxis.started += instance.OnTriggerAxis;
                    @TriggerAxis.performed += instance.OnTriggerAxis;
                    @TriggerAxis.canceled += instance.OnTriggerAxis;
                    @TriggerButton.started += instance.OnTriggerButton;
                    @TriggerButton.performed += instance.OnTriggerButton;
                    @TriggerButton.canceled += instance.OnTriggerButton;
                    @TriggerTouch.started += instance.OnTriggerTouch;
                    @TriggerTouch.performed += instance.OnTriggerTouch;
                    @TriggerTouch.canceled += instance.OnTriggerTouch;
                    @ThumbAxis.started += instance.OnThumbAxis;
                    @ThumbAxis.performed += instance.OnThumbAxis;
                    @ThumbAxis.canceled += instance.OnThumbAxis;
                    @PadAxis.started += instance.OnPadAxis;
                    @PadAxis.performed += instance.OnPadAxis;
                    @PadAxis.canceled += instance.OnPadAxis;
                    @PadButton.started += instance.OnPadButton;
                    @PadButton.performed += instance.OnPadButton;
                    @PadButton.canceled += instance.OnPadButton;
                    @PadTouch.started += instance.OnPadTouch;
                    @PadTouch.performed += instance.OnPadTouch;
                    @PadTouch.canceled += instance.OnPadTouch;
                    @GripAxis.started += instance.OnGripAxis;
                    @GripAxis.performed += instance.OnGripAxis;
                    @GripAxis.canceled += instance.OnGripAxis;
                    @GripButton.started += instance.OnGripButton;
                    @GripButton.performed += instance.OnGripButton;
                    @GripButton.canceled += instance.OnGripButton;
                    @PrimaryTouch.started += instance.OnPrimaryTouch;
                    @PrimaryTouch.performed += instance.OnPrimaryTouch;
                    @PrimaryTouch.canceled += instance.OnPrimaryTouch;
                    @PrimaryButton.started += instance.OnPrimaryButton;
                    @PrimaryButton.performed += instance.OnPrimaryButton;
                    @PrimaryButton.canceled += instance.OnPrimaryButton;
                    @SecondaryTouch.started += instance.OnSecondaryTouch;
                    @SecondaryTouch.performed += instance.OnSecondaryTouch;
                    @SecondaryTouch.canceled += instance.OnSecondaryTouch;
                    @SecondaryButton.started += instance.OnSecondaryButton;
                    @SecondaryButton.performed += instance.OnSecondaryButton;
                    @SecondaryButton.canceled += instance.OnSecondaryButton;
                }
            }
        }
        public BrushActions @Brush => new BrushActions(this);

        // Wand
        private readonly InputActionMap m_Wand;
        private IWandActions m_WandActionsCallbackInterface;
        private readonly InputAction m_Wand_TriggerAxis;
        private readonly InputAction m_Wand_TriggerButton;
        private readonly InputAction m_Wand_TriggerTouch;
        private readonly InputAction m_Wand_ThumbAxis;
        private readonly InputAction m_Wand_PadAxis;
        private readonly InputAction m_Wand_PadButton;
        private readonly InputAction m_Wand_PadTouch;
        private readonly InputAction m_Wand_GripAxis;
        private readonly InputAction m_Wand_GripButton;
        private readonly InputAction m_Wand_PrimaryTouch;
        private readonly InputAction m_Wand_PrimaryButton;
        private readonly InputAction m_Wand_SecondaryTouch;
        private readonly InputAction m_Wand_SecondaryButton;
        public struct WandActions
        {
            private @UnityXRInputAction m_Wrapper;
            public WandActions(@UnityXRInputAction wrapper) { m_Wrapper = wrapper; }
            public InputAction @TriggerAxis => m_Wrapper.m_Wand_TriggerAxis;
            public InputAction @TriggerButton => m_Wrapper.m_Wand_TriggerButton;
            public InputAction @TriggerTouch => m_Wrapper.m_Wand_TriggerTouch;
            public InputAction @ThumbAxis => m_Wrapper.m_Wand_ThumbAxis;
            public InputAction @PadAxis => m_Wrapper.m_Wand_PadAxis;
            public InputAction @PadButton => m_Wrapper.m_Wand_PadButton;
            public InputAction @PadTouch => m_Wrapper.m_Wand_PadTouch;
            public InputAction @GripAxis => m_Wrapper.m_Wand_GripAxis;
            public InputAction @GripButton => m_Wrapper.m_Wand_GripButton;
            public InputAction @PrimaryTouch => m_Wrapper.m_Wand_PrimaryTouch;
            public InputAction @PrimaryButton => m_Wrapper.m_Wand_PrimaryButton;
            public InputAction @SecondaryTouch => m_Wrapper.m_Wand_SecondaryTouch;
            public InputAction @SecondaryButton => m_Wrapper.m_Wand_SecondaryButton;
            public InputActionMap Get() { return m_Wrapper.m_Wand; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(WandActions set) { return set.Get(); }
            public void SetCallbacks(IWandActions instance)
            {
                if (m_Wrapper.m_WandActionsCallbackInterface != null)
                {
                    @TriggerAxis.started -= m_Wrapper.m_WandActionsCallbackInterface.OnTriggerAxis;
                    @TriggerAxis.performed -= m_Wrapper.m_WandActionsCallbackInterface.OnTriggerAxis;
                    @TriggerAxis.canceled -= m_Wrapper.m_WandActionsCallbackInterface.OnTriggerAxis;
                    @TriggerButton.started -= m_Wrapper.m_WandActionsCallbackInterface.OnTriggerButton;
                    @TriggerButton.performed -= m_Wrapper.m_WandActionsCallbackInterface.OnTriggerButton;
                    @TriggerButton.canceled -= m_Wrapper.m_WandActionsCallbackInterface.OnTriggerButton;
                    @TriggerTouch.started -= m_Wrapper.m_WandActionsCallbackInterface.OnTriggerTouch;
                    @TriggerTouch.performed -= m_Wrapper.m_WandActionsCallbackInterface.OnTriggerTouch;
                    @TriggerTouch.canceled -= m_Wrapper.m_WandActionsCallbackInterface.OnTriggerTouch;
                    @ThumbAxis.started -= m_Wrapper.m_WandActionsCallbackInterface.OnThumbAxis;
                    @ThumbAxis.performed -= m_Wrapper.m_WandActionsCallbackInterface.OnThumbAxis;
                    @ThumbAxis.canceled -= m_Wrapper.m_WandActionsCallbackInterface.OnThumbAxis;
                    @PadAxis.started -= m_Wrapper.m_WandActionsCallbackInterface.OnPadAxis;
                    @PadAxis.performed -= m_Wrapper.m_WandActionsCallbackInterface.OnPadAxis;
                    @PadAxis.canceled -= m_Wrapper.m_WandActionsCallbackInterface.OnPadAxis;
                    @PadButton.started -= m_Wrapper.m_WandActionsCallbackInterface.OnPadButton;
                    @PadButton.performed -= m_Wrapper.m_WandActionsCallbackInterface.OnPadButton;
                    @PadButton.canceled -= m_Wrapper.m_WandActionsCallbackInterface.OnPadButton;
                    @PadTouch.started -= m_Wrapper.m_WandActionsCallbackInterface.OnPadTouch;
                    @PadTouch.performed -= m_Wrapper.m_WandActionsCallbackInterface.OnPadTouch;
                    @PadTouch.canceled -= m_Wrapper.m_WandActionsCallbackInterface.OnPadTouch;
                    @GripAxis.started -= m_Wrapper.m_WandActionsCallbackInterface.OnGripAxis;
                    @GripAxis.performed -= m_Wrapper.m_WandActionsCallbackInterface.OnGripAxis;
                    @GripAxis.canceled -= m_Wrapper.m_WandActionsCallbackInterface.OnGripAxis;
                    @GripButton.started -= m_Wrapper.m_WandActionsCallbackInterface.OnGripButton;
                    @GripButton.performed -= m_Wrapper.m_WandActionsCallbackInterface.OnGripButton;
                    @GripButton.canceled -= m_Wrapper.m_WandActionsCallbackInterface.OnGripButton;
                    @PrimaryTouch.started -= m_Wrapper.m_WandActionsCallbackInterface.OnPrimaryTouch;
                    @PrimaryTouch.performed -= m_Wrapper.m_WandActionsCallbackInterface.OnPrimaryTouch;
                    @PrimaryTouch.canceled -= m_Wrapper.m_WandActionsCallbackInterface.OnPrimaryTouch;
                    @PrimaryButton.started -= m_Wrapper.m_WandActionsCallbackInterface.OnPrimaryButton;
                    @PrimaryButton.performed -= m_Wrapper.m_WandActionsCallbackInterface.OnPrimaryButton;
                    @PrimaryButton.canceled -= m_Wrapper.m_WandActionsCallbackInterface.OnPrimaryButton;
                    @SecondaryTouch.started -= m_Wrapper.m_WandActionsCallbackInterface.OnSecondaryTouch;
                    @SecondaryTouch.performed -= m_Wrapper.m_WandActionsCallbackInterface.OnSecondaryTouch;
                    @SecondaryTouch.canceled -= m_Wrapper.m_WandActionsCallbackInterface.OnSecondaryTouch;
                    @SecondaryButton.started -= m_Wrapper.m_WandActionsCallbackInterface.OnSecondaryButton;
                    @SecondaryButton.performed -= m_Wrapper.m_WandActionsCallbackInterface.OnSecondaryButton;
                    @SecondaryButton.canceled -= m_Wrapper.m_WandActionsCallbackInterface.OnSecondaryButton;
                }
                m_Wrapper.m_WandActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @TriggerAxis.started += instance.OnTriggerAxis;
                    @TriggerAxis.performed += instance.OnTriggerAxis;
                    @TriggerAxis.canceled += instance.OnTriggerAxis;
                    @TriggerButton.started += instance.OnTriggerButton;
                    @TriggerButton.performed += instance.OnTriggerButton;
                    @TriggerButton.canceled += instance.OnTriggerButton;
                    @TriggerTouch.started += instance.OnTriggerTouch;
                    @TriggerTouch.performed += instance.OnTriggerTouch;
                    @TriggerTouch.canceled += instance.OnTriggerTouch;
                    @ThumbAxis.started += instance.OnThumbAxis;
                    @ThumbAxis.performed += instance.OnThumbAxis;
                    @ThumbAxis.canceled += instance.OnThumbAxis;
                    @PadAxis.started += instance.OnPadAxis;
                    @PadAxis.performed += instance.OnPadAxis;
                    @PadAxis.canceled += instance.OnPadAxis;
                    @PadButton.started += instance.OnPadButton;
                    @PadButton.performed += instance.OnPadButton;
                    @PadButton.canceled += instance.OnPadButton;
                    @PadTouch.started += instance.OnPadTouch;
                    @PadTouch.performed += instance.OnPadTouch;
                    @PadTouch.canceled += instance.OnPadTouch;
                    @GripAxis.started += instance.OnGripAxis;
                    @GripAxis.performed += instance.OnGripAxis;
                    @GripAxis.canceled += instance.OnGripAxis;
                    @GripButton.started += instance.OnGripButton;
                    @GripButton.performed += instance.OnGripButton;
                    @GripButton.canceled += instance.OnGripButton;
                    @PrimaryTouch.started += instance.OnPrimaryTouch;
                    @PrimaryTouch.performed += instance.OnPrimaryTouch;
                    @PrimaryTouch.canceled += instance.OnPrimaryTouch;
                    @PrimaryButton.started += instance.OnPrimaryButton;
                    @PrimaryButton.performed += instance.OnPrimaryButton;
                    @PrimaryButton.canceled += instance.OnPrimaryButton;
                    @SecondaryTouch.started += instance.OnSecondaryTouch;
                    @SecondaryTouch.performed += instance.OnSecondaryTouch;
                    @SecondaryTouch.canceled += instance.OnSecondaryTouch;
                    @SecondaryButton.started += instance.OnSecondaryButton;
                    @SecondaryButton.performed += instance.OnSecondaryButton;
                    @SecondaryButton.canceled += instance.OnSecondaryButton;
                }
            }
        }
        public WandActions @Wand => new WandActions(this);
        private int m_IndexControllerSchemeIndex = -1;
        public InputControlScheme IndexControllerScheme
        {
            get
            {
                if (m_IndexControllerSchemeIndex == -1) m_IndexControllerSchemeIndex = asset.FindControlSchemeIndex("Index Controller");
                return asset.controlSchemes[m_IndexControllerSchemeIndex];
            }
        }
        private int m_HTCViveControllerSchemeIndex = -1;
        public InputControlScheme HTCViveControllerScheme
        {
            get
            {
                if (m_HTCViveControllerSchemeIndex == -1) m_HTCViveControllerSchemeIndex = asset.FindControlSchemeIndex("HTC Vive Controller");
                return asset.controlSchemes[m_HTCViveControllerSchemeIndex];
            }
        }
        private int m_OculusTouchControllerSchemeIndex = -1;
        public InputControlScheme OculusTouchControllerScheme
        {
            get
            {
                if (m_OculusTouchControllerSchemeIndex == -1) m_OculusTouchControllerSchemeIndex = asset.FindControlSchemeIndex("Oculus Touch Controller");
                return asset.controlSchemes[m_OculusTouchControllerSchemeIndex];
            }
        }
        private int m_WMRControllerSchemeIndex = -1;
        public InputControlScheme WMRControllerScheme
        {
            get
            {
                if (m_WMRControllerSchemeIndex == -1) m_WMRControllerSchemeIndex = asset.FindControlSchemeIndex("WMR Controller");
                return asset.controlSchemes[m_WMRControllerSchemeIndex];
            }
        }
        public interface IBrushActions
        {
            void OnTriggerAxis(InputAction.CallbackContext context);
            void OnTriggerButton(InputAction.CallbackContext context);
            void OnTriggerTouch(InputAction.CallbackContext context);
            void OnThumbAxis(InputAction.CallbackContext context);
            void OnPadAxis(InputAction.CallbackContext context);
            void OnPadButton(InputAction.CallbackContext context);
            void OnPadTouch(InputAction.CallbackContext context);
            void OnGripAxis(InputAction.CallbackContext context);
            void OnGripButton(InputAction.CallbackContext context);
            void OnPrimaryTouch(InputAction.CallbackContext context);
            void OnPrimaryButton(InputAction.CallbackContext context);
            void OnSecondaryTouch(InputAction.CallbackContext context);
            void OnSecondaryButton(InputAction.CallbackContext context);
        }
        public interface IWandActions
        {
            void OnTriggerAxis(InputAction.CallbackContext context);
            void OnTriggerButton(InputAction.CallbackContext context);
            void OnTriggerTouch(InputAction.CallbackContext context);
            void OnThumbAxis(InputAction.CallbackContext context);
            void OnPadAxis(InputAction.CallbackContext context);
            void OnPadButton(InputAction.CallbackContext context);
            void OnPadTouch(InputAction.CallbackContext context);
            void OnGripAxis(InputAction.CallbackContext context);
            void OnGripButton(InputAction.CallbackContext context);
            void OnPrimaryTouch(InputAction.CallbackContext context);
            void OnPrimaryButton(InputAction.CallbackContext context);
            void OnSecondaryTouch(InputAction.CallbackContext context);
            void OnSecondaryButton(InputAction.CallbackContext context);
        }
    }
}
