#if UNITY_EDITOR || FBXSDK_RUNTIME
//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Autodesk.Fbx {

public enum EFbxType {
  eFbxUndefined,
  eFbxChar,
  eFbxUChar,
  eFbxShort,
  eFbxUShort,
  eFbxUInt,
  eFbxLongLong,
  eFbxULongLong,
  eFbxHalfFloat,
  eFbxBool,
  eFbxInt,
  eFbxFloat,
  eFbxDouble,
  eFbxDouble2,
  eFbxDouble3,
  eFbxDouble4,
  eFbxDouble4x4,
  eFbxEnum = 17,
  eFbxEnumM = -17,
  eFbxString = 18,
  eFbxTime,
  eFbxReference,
  eFbxBlob,
  eFbxDistance,
  eFbxDateTime,
  eFbxTypeCount = 24
}

}

#endif // UNITY_EDITOR || FBXSDK_RUNTIME