#if UNITY_EDITOR || FBXSDK_RUNTIME
//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Autodesk.Fbx {

public class FbxDouble4x4 : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal FbxDouble4x4(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FbxDouble4x4 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~FbxDouble4x4() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NativeMethods.delete_FbxDouble4x4(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public FbxDouble4x4() : this(NativeMethods.new_FbxDouble4x4__SWIG_0(), true) {
  }

  public FbxDouble4x4(FbxDouble4 pValue) : this(NativeMethods.new_FbxDouble4x4__SWIG_1(pValue), true) {
  }

  public FbxDouble4x4(FbxDouble4 pData0, FbxDouble4 pData1, FbxDouble4 pData2, FbxDouble4 pData3) : this(NativeMethods.new_FbxDouble4x4__SWIG_2(pData0, pData1, pData2, pData3), true) {
  }

  private bool _equals(FbxDouble4x4 pVector) {
    bool ret = NativeMethods.FbxDouble4x4__equals(swigCPtr, FbxDouble4x4.getCPtr(pVector));
    if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxDouble4x4(FbxDouble4x4 other) : this(NativeMethods.new_FbxDouble4x4__SWIG_3(FbxDouble4x4.getCPtr(other)), true) {
    if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
  }

  public bool Equals(FbxDouble4x4 other) {
    if (object.ReferenceEquals(other, null)) { return false; }
    return _equals(other);
  }

  public override bool Equals(object obj){
    if (object.ReferenceEquals(obj, null)) { return false; }
    /* is obj a subclass of this type; if so use our Equals */
    var typed = obj as FbxDouble4x4;
    if (!object.ReferenceEquals(typed, null)) {
      return this.Equals(typed);
    }
    /* are we a subclass of the other type; if so use their Equals */
    if (typeof(FbxDouble4x4).IsSubclassOf(obj.GetType())) {
      return obj.Equals(this);
    }
    /* types are unrelated; can't be a match */
    return false;
  }

  public static bool operator == (FbxDouble4x4 a, FbxDouble4x4 b) {
    if (object.ReferenceEquals(a, b)) { return true; }
    if (object.ReferenceEquals(a, null) || object.ReferenceEquals(b, null)) { return false; }
    return a.Equals(b);
  }

  public static bool operator != (FbxDouble4x4 a, FbxDouble4x4 b) {
    return !(a == b);
  }

  public override int GetHashCode() {
    uint hash = 0;
    for(int i = 0; i < 4; ++i) {
      hash = (hash << (32 / 4)) | (hash >> (32 - (32 / 4)));
      hash ^= (uint)this[i].GetHashCode();
    }
    return (int)hash;
  }

  public override string ToString() {
    var builder = new System.Text.StringBuilder("FbxDouble4x4(");
    for(int i = 0; i < 4; ++i) {
      builder.Append(this[i].ToString());
      builder.Append(',');
    }
    builder.Replace(',', ')', builder.Length - 1, 1);
    return builder.ToString();
  }
  
  private FbxDouble4 _get(int i) {
    var ret = NativeMethods.FbxDouble4x4__get(swigCPtr, i);
    if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
    return ret;
  }

  private void _set(int i, FbxDouble4 v) {
    NativeMethods.FbxDouble4x4__set(swigCPtr, i, v);
    if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
  }

  public FbxDouble4 this[int index] {
    get {
      if (index < 0 || index >= 4) {
        throw new System.ArgumentOutOfRangeException("index");
      } else {
        return this._get(index);
      }
    }
    set {
      if (index < 0 || index >= 4) {
        throw new System.ArgumentOutOfRangeException("index");
      } else {
        this._set(index, value);
      }
    }
  }
  
  public FbxDouble4 X {
    get { return this._get(0); }
    set { this._set(0, value); }
  }
  
  public FbxDouble4 Y {
    get { return this._get(1); }
    set { this._set(1, value); }
  }
  
  public FbxDouble4 Z {
    get { return this._get(2); }
    set { this._set(2, value); }
  }
  
  public FbxDouble4 W {
    get { return this._get(3); }
    set { this._set(3, value); }
  }
  
}

}

#endif // UNITY_EDITOR || FBXSDK_RUNTIME