#if UNITY_EDITOR || FBXSDK_RUNTIME
//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Autodesk.Fbx {

public class FbxExporter : FbxIOBase {
  internal FbxExporter(global::System.IntPtr cPtr, bool ignored) : base(cPtr, ignored) { }

  // override void Dispose() {base.Dispose();}

  public new static FbxExporter Create(FbxManager pManager, string pName) {
    global::System.IntPtr cPtr = NativeMethods.FbxExporter_Create__SWIG_0(FbxManager.getCPtr(pManager), pName);
    FbxExporter ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxExporter(cPtr, false);
    if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
    return ret;
  }

  public new static FbxExporter Create(FbxObject pContainer, string pName) {
    global::System.IntPtr cPtr = NativeMethods.FbxExporter_Create__SWIG_1(FbxObject.getCPtr(pContainer), pName);
    FbxExporter ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxExporter(cPtr, false);
    if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool Export(FbxDocument pDocument) {
    bool ret = NativeMethods.FbxExporter_Export(swigCPtr, FbxDocument.getCPtr(pDocument));
    if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool SetFileExportVersion(string pVersion) {
    bool ret = NativeMethods.FbxExporter_SetFileExportVersion(swigCPtr, pVersion);
    if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxIOFileHeaderInfo GetFileHeaderInfo() {
    global::System.IntPtr cPtr = NativeMethods.FbxExporter_GetFileHeaderInfo(swigCPtr);
    FbxIOFileHeaderInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxIOFileHeaderInfo(cPtr, false);
    if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
    return ret;
  }

  public override int GetHashCode(){
      return swigCPtr.Handle.GetHashCode();
  }

  public bool Equals(FbxExporter other) {
    if (object.ReferenceEquals(other, null)) { return false; }
    return this.swigCPtr.Handle.Equals (other.swigCPtr.Handle);
  }

  public override bool Equals(object obj){
    if (object.ReferenceEquals(obj, null)) { return false; }
    /* is obj a subclass of this type; if so use our Equals */
    var typed = obj as FbxExporter;
    if (!object.ReferenceEquals(typed, null)) {
      return this.Equals(typed);
    }
    /* are we a subclass of the other type; if so use their Equals */
    if (typeof(FbxExporter).IsSubclassOf(obj.GetType())) {
      return obj.Equals(this);
    }
    /* types are unrelated; can't be a match */
    return false;
  }

  public static bool operator == (FbxExporter a, FbxExporter b) {
    if (object.ReferenceEquals(a, b)) { return true; }
    if (object.ReferenceEquals(a, null) || object.ReferenceEquals(b, null)) { return false; }
    return a.Equals(b);
  }

  public static bool operator != (FbxExporter a, FbxExporter b) {
    return !(a == b);
  }

  private void SetFbxSharpProgressCallback(FbxSharpProgressCallback callback) {
    NativeMethods.FbxExporter_SetFbxSharpProgressCallback(swigCPtr, FbxSharpProgressCallback.getCPtr(callback));
    if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
  }

  FbxSharpProgressCallback m_progressCallback;

  public void SetProgressCallback(Globals.FbxProgressCallback callback) {
    if (m_progressCallback != null) { m_progressCallback.Dispose(); }
    m_progressCallback = (callback == null) ? null : new FbxSharpProgressCallback.Wrapper(callback);
    SetFbxSharpProgressCallback(m_progressCallback);
  } 
  private int _getCurrentWritableVersionsLength() {
    int ret = NativeMethods.FbxExporter__getCurrentWritableVersionsLength(swigCPtr);
    if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
    return ret;
  }

  private string _getCurrentWritableVersionByIndex(int i) {
    string ret = NativeMethods.FbxExporter__getCurrentWritableVersionByIndex(swigCPtr, i);
    if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
    return ret;
  }

  public string[] GetCurrentWritableVersions() {
    var versions = new string[_getCurrentWritableVersionsLength()];
    for(int i = 0, n = versions.Length; i < n; ++i) {
      versions[i] = _getCurrentWritableVersionByIndex(i);
    }
    return versions;
  }
  
}

}

#endif // UNITY_EDITOR || FBXSDK_RUNTIME