#if UNITY_EDITOR || FBXSDK_RUNTIME
//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Autodesk.Fbx {

public class FbxGeometryBase : FbxLayerContainer {
  internal FbxGeometryBase(global::System.IntPtr cPtr, bool ignored) : base(cPtr, ignored) { }

  // override void Dispose() {base.Dispose();}

  public new static FbxGeometryBase Create(FbxManager pManager, string pName) {
    global::System.IntPtr cPtr = NativeMethods.FbxGeometryBase_Create__SWIG_0(FbxManager.getCPtr(pManager), pName);
    FbxGeometryBase ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxGeometryBase(cPtr, false);
    if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
    return ret;
  }

  public new static FbxGeometryBase Create(FbxObject pContainer, string pName) {
    global::System.IntPtr cPtr = NativeMethods.FbxGeometryBase_Create__SWIG_1(FbxObject.getCPtr(pContainer), pName);
    FbxGeometryBase ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxGeometryBase(cPtr, false);
    if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void InitControlPoints(int pCount) {
    NativeMethods.FbxGeometryBase_InitControlPoints(swigCPtr, pCount);
    if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
  }

  public virtual int GetControlPointsCount() {
    int ret = NativeMethods.FbxGeometryBase_GetControlPointsCount(swigCPtr);
    if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxPropertyDouble3 BBoxMin {
    get {
      FbxPropertyDouble3 ret = new FbxPropertyDouble3(NativeMethods.FbxGeometryBase_BBoxMin_get(swigCPtr), false);
      if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public FbxPropertyDouble3 BBoxMax {
    get {
      FbxPropertyDouble3 ret = new FbxPropertyDouble3(NativeMethods.FbxGeometryBase_BBoxMax_get(swigCPtr), false);
      if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public void ComputeBBox() {
    NativeMethods.FbxGeometryBase_ComputeBBox(swigCPtr);
    if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
  }

  public FbxLayerElementNormal CreateElementNormal() {
    global::System.IntPtr cPtr = NativeMethods.FbxGeometryBase_CreateElementNormal(swigCPtr);
    FbxLayerElementNormal ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxLayerElementNormal(cPtr, false);
    if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxLayerElementTangent CreateElementTangent() {
    global::System.IntPtr cPtr = NativeMethods.FbxGeometryBase_CreateElementTangent(swigCPtr);
    FbxLayerElementTangent ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxLayerElementTangent(cPtr, false);
    if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
    return ret;
  }

  public override int GetHashCode(){
      return swigCPtr.Handle.GetHashCode();
  }

  public bool Equals(FbxGeometryBase other) {
    if (object.ReferenceEquals(other, null)) { return false; }
    return this.swigCPtr.Handle.Equals (other.swigCPtr.Handle);
  }

  public override bool Equals(object obj){
    if (object.ReferenceEquals(obj, null)) { return false; }
    /* is obj a subclass of this type; if so use our Equals */
    var typed = obj as FbxGeometryBase;
    if (!object.ReferenceEquals(typed, null)) {
      return this.Equals(typed);
    }
    /* are we a subclass of the other type; if so use their Equals */
    if (typeof(FbxGeometryBase).IsSubclassOf(obj.GetType())) {
      return obj.Equals(this);
    }
    /* types are unrelated; can't be a match */
    return false;
  }

  public static bool operator == (FbxGeometryBase a, FbxGeometryBase b) {
    if (object.ReferenceEquals(a, b)) { return true; }
    if (object.ReferenceEquals(a, null) || object.ReferenceEquals(b, null)) { return false; }
    return a.Equals(b);
  }

  public static bool operator != (FbxGeometryBase a, FbxGeometryBase b) {
    return !(a == b);
  }

  public void SetControlPointAt(FbxVector4 pCtrlPoint, int pIndex) {
    NativeMethods.FbxGeometryBase_SetControlPointAt(swigCPtr, pCtrlPoint, pIndex);
    if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
  }

  public FbxVector4 GetControlPointAt(int pIndex) {
    var ret = NativeMethods.FbxGeometryBase_GetControlPointAt(swigCPtr, pIndex);
    if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
    return ret;
  }

}

}

#endif // UNITY_EDITOR || FBXSDK_RUNTIME