#if UNITY_EDITOR || FBXSDK_RUNTIME
//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Autodesk.Fbx {

public class FbxLayerElementArray : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal FbxLayerElementArray(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FbxLayerElementArray obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~FbxLayerElementArray() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NativeMethods.delete_FbxLayerElementArray(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public FbxLayerElementArray(EFbxType pDataType) : this(NativeMethods.new_FbxLayerElementArray((int)pDataType), true) {
  }

  public int GetCount() {
    int ret = NativeMethods.FbxLayerElementArray_GetCount(swigCPtr);
    if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetCount(int pCount) {
    NativeMethods.FbxLayerElementArray_SetCount(swigCPtr, pCount);
    if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
  }

  public int Add(int pItem) {
    int ret = NativeMethods.FbxLayerElementArray_Add__SWIG_1(swigCPtr, pItem);
    if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
    return ret;
  }

  public int Add(FbxColor pItem) {
    int ret = NativeMethods.FbxLayerElementArray_Add__SWIG_2(swigCPtr, pItem);
    if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
    return ret;
  }

  public int Add(FbxVector2 pItem) {
    int ret = NativeMethods.FbxLayerElementArray_Add__SWIG_3(swigCPtr, pItem);
    if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
    return ret;
  }

  public int Add(FbxVector4 pItem) {
    int ret = NativeMethods.FbxLayerElementArray_Add__SWIG_4(swigCPtr, pItem);
    if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetAt(int pIndex, int pItem) {
    NativeMethods.FbxLayerElementArray_SetAt__SWIG_1(swigCPtr, pIndex, pItem);
    if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
  }

  public void SetAt(int pIndex, FbxColor pItem) {
    NativeMethods.FbxLayerElementArray_SetAt__SWIG_2(swigCPtr, pIndex, pItem);
    if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
  }

  public void SetAt(int pIndex, FbxVector2 pItem) {
    NativeMethods.FbxLayerElementArray_SetAt__SWIG_3(swigCPtr, pIndex, pItem);
    if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
  }

  public void SetAt(int pIndex, FbxVector4 pItem) {
    NativeMethods.FbxLayerElementArray_SetAt__SWIG_4(swigCPtr, pIndex, pItem);
    if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
  }

}

}

#endif // UNITY_EDITOR || FBXSDK_RUNTIME