#if UNITY_EDITOR || FBXSDK_RUNTIME
//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Autodesk.Fbx {

public class FbxNull : FbxNodeAttribute {
  internal FbxNull(global::System.IntPtr cPtr, bool ignored) : base(cPtr, ignored) { }

  // override void Dispose() {base.Dispose();}

  public new static FbxNull Create(FbxManager pManager, string pName) {
    global::System.IntPtr cPtr = NativeMethods.FbxNull_Create__SWIG_0(FbxManager.getCPtr(pManager), pName);
    FbxNull ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxNull(cPtr, false);
    if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
    return ret;
  }

  public new static FbxNull Create(FbxObject pContainer, string pName) {
    global::System.IntPtr cPtr = NativeMethods.FbxNull_Create__SWIG_1(FbxObject.getCPtr(pContainer), pName);
    FbxNull ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxNull(cPtr, false);
    if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reset() {
    NativeMethods.FbxNull_Reset(swigCPtr);
    if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
  }

  public double GetSizeDefaultValue() {
    double ret = NativeMethods.FbxNull_GetSizeDefaultValue(swigCPtr);
    if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string sSize {
    get {
      string ret = NativeMethods.FbxNull_sSize_get();
      return ret;
    } 
  }

  public static string sLook {
    get {
      string ret = NativeMethods.FbxNull_sLook_get();
      return ret;
    } 
  }

  public static double sDefaultSize {
    get {
      double ret = NativeMethods.FbxNull_sDefaultSize_get();
      return ret;
    } 
  }

  public static FbxNull.ELook sDefaultLook {
    get {
      FbxNull.ELook ret = (FbxNull.ELook)NativeMethods.FbxNull_sDefaultLook_get();
      return ret;
    } 
  }

  public FbxPropertyDouble Size {
    get {
      FbxPropertyDouble ret = new FbxPropertyDouble(NativeMethods.FbxNull_Size_get(swigCPtr), false);
      if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public FbxPropertyNullELook Look {
    get {
      FbxPropertyNullELook ret = new FbxPropertyNullELook(NativeMethods.FbxNull_Look_get(swigCPtr), false);
      if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public override int GetHashCode(){
      return swigCPtr.Handle.GetHashCode();
  }

  public bool Equals(FbxNull other) {
    if (object.ReferenceEquals(other, null)) { return false; }
    return this.swigCPtr.Handle.Equals (other.swigCPtr.Handle);
  }

  public override bool Equals(object obj){
    if (object.ReferenceEquals(obj, null)) { return false; }
    /* is obj a subclass of this type; if so use our Equals */
    var typed = obj as FbxNull;
    if (!object.ReferenceEquals(typed, null)) {
      return this.Equals(typed);
    }
    /* are we a subclass of the other type; if so use their Equals */
    if (typeof(FbxNull).IsSubclassOf(obj.GetType())) {
      return obj.Equals(this);
    }
    /* types are unrelated; can't be a match */
    return false;
  }

  public static bool operator == (FbxNull a, FbxNull b) {
    if (object.ReferenceEquals(a, b)) { return true; }
    if (object.ReferenceEquals(a, null) || object.ReferenceEquals(b, null)) { return false; }
    return a.Equals(b);
  }

  public static bool operator != (FbxNull a, FbxNull b) {
    return !(a == b);
  }

  public enum ELook {
    eNone,
    eCross
  }

}

}

#endif // UNITY_EDITOR || FBXSDK_RUNTIME