function path.fromSvg(svgPathString) end
function paths.fromSvg(svgPathString) end
function brush.pastPosition(back) end
function brush.pastRotation(back) end
function wand.pastPosition(back) end
function wand.pastRotation(back) end
function head.pastPosition(back) end
function head.pastRotation(back) end
function path.transform(path, tr) end
function path.translate(path, translation) end
function path.rotate(path, rotation) end
function path.scale(path, scale) end
function vector.vectorToRotation(vec) end
function vector.rotationToVector(rot) end
function draw.path(path) end
function draw.paths(paths) end
function draw.polygon(sides, radius, angle) end
function draw.text(text) end
function draw.svg(svgPathString) end
function brush.type(brushType) end
function color.addHsv(hsv) end
function color.addRgb(rgb) end
function color.setRgb(rgb) end
function color.setHsv(hsv) end
function color.setHtml(color) end
function color.jitter() end
function brush.sizeSet(size) end
function brush.sizeAdd(amount) end
function draw.camerapath(index) end
function listenfor.strokes(url) end
function showfolder.scripts() end
function showfolder.exports() end
function spectator.moveTo(position) end
function user.moveTo(position) end
function spectator.moveBy(amount) end
function user.moveBy(amount) end
function spectator.turnY(angle) end
function spectator.turnX(angle) end
function spectator.turnY(angle) end
function spectator.direction(direction) end
function spectator.lookAt(position) end
function spectator.mode(mode) end
function spectator.show(thing) end
function spectator.hide(thing) end
function debug.brush() end
function image.import(location) end
function environment.type(name) end
function layer.add() end
function layer.clear(layer) end
function layer.delete(layer) end
function layer.squash(squashedLayer, destinationLayer) end
function layer.activate(layer) end
function layer.show(layer) end
function layer.hide(layer) end
function layer.toggle(layer) end
function model.select(index) end
function model.position(index, position) end
function brush.forcePaintingOn(active) end
function brush.forcePaintingOff(active) end
function image.position(index, position) end
function guide.add(type) end
function save.overwrite() end
function save.new() end
function export.all() end
function drafting.visible() end
function drafting.transparent() end
function drafting.hidden() end
function merge.named(filename) end
function symmetry.mirror() end
function symmetry.doublemirror() end
function twohandeded.toggle() end
function straightedge.toggle() end
function autoorient.toggle() end
function undo() end
function redo() end
function panels.reset() end
function sketch.origin() end
function viewonly.toggle() end
function spectator.toggle() end
function spectator.on() end
function spectator.off() end
function autosimplify.toggle() end
function export.current() end
function showfolder.sketch(index) end
function guides.disable() end
function disco() end
function selection.duplicate() end
function selection.group() end
function export.selected() end
function camerapath.render() end
function profiling.toggle() end
function settings.toggle() end
function mirror.summon() end
function symmetry.setPosition(position) end
function symmetry.setTransform(position, rotation) end
function selection.invert() end
function selection.flip() end
function postprocessing.toggle() end
function watermark.toggle() end
function camerapath.togglevisuals() end
function camerapath.togglepreview() end
function camerapath.delete() end
function camerapath.record() end
function stroke.delete(index) end
function stroke.select(index) end
function strokes.select(from, to) end
function selection.recolor() end
function selection.rebrush() end
function selection.resize() end
function selection.trim(count) end
function selection.pointsPerlin(axis, scale) end
function stroke.pointsQuantize(grid) end
function stroke.join() end
function strokes.join(from, to) end
function stroke.add(index) end
tool.startPosition = nil
tool.endPosition = nil
tool.vector = nil
brush.timeSincePressed = nil
brush.timeSinceReleased = nil
brush.triggerIsPressed = nil
brush.triggerIsPressedThisFrame = nil
brush.distanceMoved = nil
brush.distanceDrawn = nil
brush.position = nil
brush.rotation = nil
brush.direction = nil
brush.size.get = nil
brush.size01.get = nil
brush.pressure = nil
brush.name = nil
brush.speed = nil
wand.position = nil
wand.rotation = nil
wand.direction = nil
wand.pressure = nil
wand.speed = nil
brush.color = nil
brush.lastColorPicked = nil
brush.colorHsv = nil
brush.lastColorPickedHsv = nil
app.time = nil
app.frames = nil
app.lastSelectedStroke = nil
app.lastStroke = nil
canvas.scale = nil
canvas.strokeCount = nil
